// <auto-generated />
namespace Petronas.SampleApp.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SampleApp5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SampleApp5));
        
        string IMigrationMetadata.Id
        {
            get { return "201801310358320_SampleApp5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
